import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Compass, Send, ArrowLeft, Bot, User, Loader2, Download, FileText, File, Map, Tag, Award, ExternalLink, AlertTriangle, CheckCircle, TrendingUp, Briefcase } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

type Message = { role: 'user' | 'assistant'; content: string };

// Strip markdown symbols from text
function cleanMarkdown(text: string): string {
  return text
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/#{1,6}\s/g, '')
    .replace(/`{3}[\s\S]*?`{3}/g, '')
    .replace(/`/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/^[-*+]\s/gm, '• ')
    .replace(/^\d+\.\s/gm, '')
    .trim();
}

// Limit text to approximately 200 lines
function limitLines(text: string, maxLines: number = 200): string {
  const lines = text.split('\n');
  if (lines.length > maxLines) {
    return lines.slice(0, maxLines).join('\n') + '\n...';
  }
  return text;
}

// Generate PDF content
function generatePDF(content: string, title: string = 'AI Career Advisor Report') {
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; color: #333; }
          h1 { color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }
          .content { white-space: pre-wrap; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="content">${content}</div>
        <div class="footer">Generated by CareerPath AI Advisor - ${new Date().toLocaleDateString()}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }
}

// Generate DOCX content (simplified - downloads as HTML that can be opened in Word)
function generateDOCX(content: string, title: string = 'AI Career Advisor Report') {
  const htmlContent = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
    <head><meta charset="utf-8"><title>${title}</title></head>
    <body style="font-family: Arial, sans-serif;">
    <h1 style="color: #0066cc;">${title}</h1>
    <div style="white-space: pre-wrap;">${content}</div>
    <p style="margin-top: 40px; color: #666;">Generated by CareerPath AI Advisor - ${new Date().toLocaleDateString()}</p>
    </body>
    </html>
  `;
  const blob = new Blob([htmlContent], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/\s+/g, '_')}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function Advisor() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'assistant', content: "Hello! I am your AI Career Advisor. I can help you explore career paths, analyze your skills, and provide personalized guidance including:\n\n• Career Roadmaps\n• Skill Tagging (Technical, Soft Skills, Tools)\n• Experience Level Assessment\n• Reference Links & Resources\n• Risk Indicators for Career Paths\n\nWhat would you like to discuss about your career today?" }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const sendMessage = async () => {
    if (!input.trim() || isLoading) return;
    
    const userMsg: Message = { role: 'user', content: input };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    try {
      const enhancedPrompt = `${input}

Please provide a comprehensive response that includes:
1. CAREER ROADMAP: A step-by-step path with milestones
2. SKILL TAGS: Categorize skills as [Technical], [Soft Skill], [Tool], or [Certification]
3. EXPERIENCE LEVEL: Tag recommendations as (Beginner), (Intermediate), or (Advanced)
4. REFERENCE LINKS: Include relevant learning resources, articles, or certification links
5. RISK INDICATOR: For each career path or course, indicate if it is:
   - FUTURE-FOCUSED (High demand, growing field)
   - MODERATE RISK (Stable but competitive)
   - HIGH RISK/LOW DEMAND (Declining or oversaturated)

Keep the response clear, actionable, and within 200 lines. Use Indian Rupee (₹) for any salary or cost references.`;

      const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/career-advisor`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}` },
        body: JSON.stringify({ messages: [...messages, { role: 'user', content: enhancedPrompt }] }),
      });

      if (!resp.ok) throw new Error('Failed to get response');

      const reader = resp.body?.getReader();
      const decoder = new TextDecoder();
      let assistantContent = '';

      setMessages(prev => [...prev, { role: 'assistant', content: '' }]);

      while (reader) {
        const { done, value } = await reader.read();
        if (done) break;
        
        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split('\n');
        
        for (const line of lines) {
          if (line.startsWith('data: ') && line !== 'data: [DONE]') {
            try {
              const data = JSON.parse(line.slice(6));
              const content = data.choices?.[0]?.delta?.content;
              if (content) {
                assistantContent += content;
                const cleanedContent = limitLines(cleanMarkdown(assistantContent));
                setMessages(prev => {
                  const newMsgs = [...prev];
                  newMsgs[newMsgs.length - 1] = { role: 'assistant', content: cleanedContent };
                  return newMsgs;
                });
              }
            } catch {}
          }
        }
      }
    } catch (error) {
      setMessages(prev => [...prev, { role: 'assistant', content: "I am having trouble connecting. Please try again." }]);
    } finally {
      setIsLoading(false);
    }
  };

  const lastAssistantMessage = messages.filter(m => m.role === 'assistant').pop()?.content || '';

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="glass-nav border-b border-border p-4">
        <div className="container flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate('/')} className="text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div className="flex items-center gap-2">
              <div className="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center">
                <Compass className="w-5 h-5 text-primary-foreground" />
              </div>
              <div>
                <span className="font-display font-bold text-lg uppercase block">AI CAREER ADVISOR</span>
                <span className="text-xs text-muted-foreground">Powered by AI</span>
              </div>
            </div>
          </div>

          {/* Download Options */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm" className="gap-2">
                <Download className="w-4 h-4" />
                Export
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="glass-card border-border/50">
              <DropdownMenuItem onClick={() => generatePDF(lastAssistantMessage)} className="cursor-pointer">
                <FileText className="w-4 h-4 mr-2" />
                Download as PDF
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => generateDOCX(lastAssistantMessage)} className="cursor-pointer">
                <File className="w-4 h-4 mr-2" />
                Download as DOCX
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>

      {/* Feature Tags */}
      <div className="border-b border-border/50 py-3 px-4 overflow-x-auto">
        <div className="container flex items-center gap-3 text-xs">
          <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-primary/10 text-primary whitespace-nowrap">
            <Map className="w-3 h-3" />
            Career Roadmap
          </div>
          <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-blue-500/10 text-blue-400 whitespace-nowrap">
            <Tag className="w-3 h-3" />
            Skill Tagging
          </div>
          <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-purple-500/10 text-purple-400 whitespace-nowrap">
            <Award className="w-3 h-3" />
            Experience Levels
          </div>
          <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-cyan-500/10 text-cyan-400 whitespace-nowrap">
            <ExternalLink className="w-3 h-3" />
            Reference Links
          </div>
          <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-green-500/10 text-green-400 whitespace-nowrap">
            <TrendingUp className="w-3 h-3" />
            Risk Indicator
          </div>
          <div className="flex items-center gap-1 px-3 py-1.5 rounded-full bg-orange-500/10 text-orange-400 whitespace-nowrap">
            <Briefcase className="w-3 h-3" />
            Micro-Internship
          </div>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4">
        <div className="container max-w-3xl space-y-4">
          <AnimatePresence>
            {messages.map((msg, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : ''}`}
              >
                {msg.role === 'assistant' && (
                  <div className="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center flex-shrink-0 shadow-glow">
                    <Bot className="w-5 h-5 text-primary-foreground" />
                  </div>
                )}
                <div className={`max-w-[80%] rounded-2xl p-4 ${msg.role === 'user' ? 'bg-gradient-primary text-primary-foreground' : 'glass-card'}`}>
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.content}</p>
                </div>
                {msg.role === 'user' && (
                  <div className="w-10 h-10 rounded-xl bg-secondary flex items-center justify-center flex-shrink-0">
                    <User className="w-5 h-5" />
                  </div>
                )}
              </motion.div>
            ))}
          </AnimatePresence>
          {isLoading && messages[messages.length - 1]?.role === 'user' && (
            <div className="flex gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-primary flex items-center justify-center shadow-glow">
                <Loader2 className="w-5 h-5 text-primary-foreground animate-spin" />
              </div>
              <div className="glass-card rounded-2xl p-4">
                <div className="flex gap-1.5">
                  <span className="w-2 h-2 bg-primary rounded-full animate-bounce" />
                  <span className="w-2 h-2 bg-primary rounded-full animate-bounce animation-delay-200" />
                  <span className="w-2 h-2 bg-primary rounded-full animate-bounce animation-delay-400" />
                </div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input */}
      <div className="border-t border-border p-4 bg-card/50 backdrop-blur-xl">
        <div className="container max-w-3xl">
          <form onSubmit={(e) => { e.preventDefault(); sendMessage(); }} className="flex gap-3">
            <Input 
              value={input} 
              onChange={(e) => setInput(e.target.value)} 
              placeholder="Ask about careers, skills, industry trends..." 
              className="flex-1 h-12 bg-secondary/50 border-border/50 focus:border-primary" 
              disabled={isLoading} 
            />
            <Button type="submit" variant="hero" size="lg" disabled={isLoading || !input.trim()} className="h-12 px-6">
              <Send className="w-5 h-5" />
            </Button>
          </form>
          <p className="text-xs text-muted-foreground text-center mt-3">
            AI can make mistakes. Verify important career decisions with professionals.
          </p>
        </div>
      </div>
    </div>
  );
}
